name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this issue related to?
      options:
        - essential_dart
        - essential_flutter
        - both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: I expected X to happen, but Y happened instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: Please provide a minimal code snippet that reproduces the issue.
      render: dart
      placeholder: |
        void main() {
          // Your code here
        }
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Paste any relevant logs or screenshots here.
      render: shell
    validations:
      required: false

  - type: input
    id: dart-version
    attributes:
      label: Dart Version
      description: Output of `dart --version`
      placeholder: Dart SDK version: 3.0.0 ...
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: Output of `flutter --version` (if applicable)
      placeholder: Flutter 3.10.0 ...
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: macOS 13.4, Windows 11, Ubuntu 22.04...
    validations:
      required: false
