name: 📚 Documentation
description: Improvements or additions to documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What kind of documentation needs improvement?
      options:
        - API Documentation (Dartdoc)
        - README
        - Examples
        - Guides/Tutorials
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what needs to be improved.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the issue located? (e.g., specific file, class, or section)
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: If you have a specific suggestion, please describe it here.
    validations:
      required: false
